#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BackpackHolo

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BackpackHolo.BP_BackpackHolo_C
// 0x0030 (0x02D8 - 0x02A8)
class ABP_BackpackHolo_C final : public AActor
{
public:
	uint8                                         Pad_2A8[0x8];                                      // 0x02A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_Main_C*        TraceCharacter;                                    // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          CanSpawn;                                          // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C1[0x7];                                      // 0x02C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Actors_to_Ignore;                                  // 0x02C8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)

public:
	void ReceiveTick(float DeltaSeconds_ReceiveTick);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BackpackHolo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BackpackHolo_C")
	}
	static class ABP_BackpackHolo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BackpackHolo_C>();
	}
};
DUMPER7_ASSERTS_ABP_BackpackHolo_C;

SDK_NAMESPACE_END
