#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_cLeonMapSettings_Main

#include "Basic.hpp"

#include "BP_cLeonMapSettings_Main_classes.hpp"
#include "BP_cLeonMapSettings_Main_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_cLeonMapSettings_Main.BP_cLeonMapSettings_Main_C.BPI_InteractEnd
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_cLeonMapSettings_Main_C::BPI_InteractEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonMapSettings_Main_C", "BPI_InteractEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_cLeonMapSettings_Main.BP_cLeonMapSettings_Main_C.BPI_InteractStart(Local)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  First_Person                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_cLeonMapSettings_Main_C::BPI_InteractStart_Local_(class ABP_FirstPersonCharacter_Main_C* First_Person)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonMapSettings_Main_C", "BPI_InteractStart(Local)");

	Params::BP_cLeonMapSettings_Main_C_BPI_InteractStart_Local_ Parms{};

	Parms.First_Person = First_Person;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_cLeonMapSettings_Main.BP_cLeonMapSettings_Main_C.BPI_InteractStart(Server)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  First_Person                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_cLeonMapSettings_Main_C::BPI_InteractStart_Server_(class ABP_FirstPersonCharacter_Main_C* First_Person)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonMapSettings_Main_C", "BPI_InteractStart(Server)");

	Params::BP_cLeonMapSettings_Main_C_BPI_InteractStart_Server_ Parms{};

	Parms.First_Person = First_Person;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_cLeonMapSettings_Main.BP_cLeonMapSettings_Main_C.IsChangeImage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsInteract                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            OverrideText                                           (Parm, OutParm)

void ABP_cLeonMapSettings_Main_C::IsChangeImage(bool* IsInteract, class FText* OverrideText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonMapSettings_Main_C", "IsChangeImage");

	Params::BP_cLeonMapSettings_Main_C_IsChangeImage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsInteract != nullptr)
		*IsInteract = Parms.IsInteract;

	if (OverrideText != nullptr)
		*OverrideText = std::move(Parms.OverrideText);
}


// Function BP_cLeonMapSettings_Main.BP_cLeonMapSettings_Main_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_cLeonMapSettings_Main_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_cLeonMapSettings_Main_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
