#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CraftedObject_Container_Base

#include "Basic.hpp"

#include "BP_CraftedObject_Base_classes.hpp"
#include "ENUM_HandType_structs.hpp"
#include "ENUM_ClassType_structs.hpp"
#include "ENUM_ItemBindType_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CraftedObject_Container_Base.BP_CraftedObject_Container_Base_C
// 0x0008 (0x0358 - 0x0350)
class ABP_CraftedObject_Container_Base_C : public ABP_CraftedObject_Base_C
{
public:
	uint8                                         Pad_350[0x8];                                      // 0x0350(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveBeginPlay();
	void GetItemInfo(ENUM_HandType* HandType, ENUM_ClassType* ClassType, bool* NotPickUp, struct FRotator* HaveRotation, struct FVector* Add_Position, bool* IsBoneAttach, ENUM_ItemBindType* BindType, class FName* BoneName, struct FST_ItemCoreDatas* CoreDatas);
	void IsChangeImage(bool* IsInteract, class FText* OverrideText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CraftedObject_Container_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CraftedObject_Container_Base_C")
	}
	static class ABP_CraftedObject_Container_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CraftedObject_Container_Base_C>();
	}
};
DUMPER7_ASSERTS_ABP_CraftedObject_Container_Base_C;

SDK_NAMESPACE_END
