#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageTool_Base_V2

#include "Basic.hpp"

#include "BP_ItemBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DamageTool_Base_V2.BP_DamageTool_Base_V2_C
// 0x00C0 (0x0500 - 0x0440)
class ABP_DamageTool_Base_V2_C : public ABP_ItemBase_C
{
public:
	class UBPC_LongInputControl_C*                BPC_LongInputControl;                              // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_ComboControl_C*                    BPC_ComboControl;                                  // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        NowDamageMultiply;                                 // 0x0450(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        NowStanDamageMultiply;                             // 0x0458(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DamageEnableState;                                 // 0x0460(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_461[0x3];                                      // 0x0461(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   Damage_Name;                                       // 0x0464(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46C[0x4];                                      // 0x046C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Damage_Value;                                      // 0x0470(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSet<class AActor*>                           HitActors;                                         // 0x0478(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class UPrimitiveComponent*>            CollisionPrimitives;                               // 0x04C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UAnimMontage*                           DefaultMontage;                                    // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBPC_ComboControl_C*                    LocalComboControl;                                 // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_ReplicateEventController_C*         ReplicateEventController;                          // 0x04E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        ShotRange;                                         // 0x04F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_DamageTool_Base_V2_BPC_ComboControl_K2Node_ComponentBoundEvent_1_OnUniqueEvent__DelegateSignature(class FName EventName);
	void DefaultMontagePlay();
	void PickState(bool State, class ABP_FirstPersonCharacter_Main_C* Character, int32 SlotIndex);
	void SetMeshDatas(bool KeepScale);
	void Shot(bool PressState_Shot, double PushTime_Shot, class ABP_FirstPersonCharacter_Main_C* SourcePlayer_Shot);
	void ReceiveBeginPlay();
	void Attack_AC_Remote(double TimeRange, class FName ComponentName, double DamageMultiply, double StanMultiply);
	void Combo(double TimeRange, class FName ComboName);
	void Attack_AC(double TimeRange, class FName AttackName, double DamageMultiply, bool MutipleHitPossible, double StanMultiply);
	void CollisionReset();
	void OnCompleted_F05B6598419A998A4627419382E250E0(class FName NotifyName);
	void OnBlendOut_F05B6598419A998A4627419382E250E0(class FName NotifyName);
	void OnInterrupted_F05B6598419A998A4627419382E250E0(class FName NotifyName);
	void OnNotifyBegin_F05B6598419A998A4627419382E250E0(class FName NotifyName);
	void OnNotifyEnd_F05B6598419A998A4627419382E250E0(class FName NotifyName);
	void OnCompleted_09216A5F450F81DD4AA575987ACD9FD6(class FName NotifyName);
	void OnBlendOut_09216A5F450F81DD4AA575987ACD9FD6(class FName NotifyName);
	void OnInterrupted_09216A5F450F81DD4AA575987ACD9FD6(class FName NotifyName);
	void OnNotifyBegin_09216A5F450F81DD4AA575987ACD9FD6(class FName NotifyName);
	void OnNotifyEnd_09216A5F450F81DD4AA575987ACD9FD6(class FName NotifyName);
	void ApplyDamage(class UObject* OtherActor, const struct FHitResult& Sweep_Result);
	void IsChangeImage(bool* IsInteract, class FText* OverrideText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DamageTool_Base_V2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DamageTool_Base_V2_C")
	}
	static class ABP_DamageTool_Base_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DamageTool_Base_V2_C>();
	}
};
DUMPER7_ASSERTS_ABP_DamageTool_Base_V2_C;

SDK_NAMESPACE_END
