#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExitShopArea

#include "Basic.hpp"

#include "BP_PlayerCounter_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ExitShopArea.BP_ExitShopArea_C
// 0x0030 (0x0330 - 0x0300)
class ABP_ExitShopArea_C final : public ABP_PlayerCounter_Base_C
{
public:
	uint8                                         Pad_300[0x8];                                      // 0x0300(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UBoxComponent*                          Box;                                               // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         OverlapingPlayers_0;                               // 0x0310(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class ABP_GameState_LINK_C*                   As_BP_Game_State_LINK_0;                           // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonGameMode_Online_LINK_C*  As_BP_First_Person_Game_Mode_Online_LINK_0;        // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExitShopArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExitShopArea_C")
	}
	static class ABP_ExitShopArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ExitShopArea_C>();
	}
};
DUMPER7_ASSERTS_ABP_ExitShopArea_C;

SDK_NAMESPACE_END
