#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Container_Base

#include "Basic.hpp"

#include "BP_EnvironmentSystem_Container_Base_classes.hpp"
#include "BP_EnvironmentSystem_Container_Base_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_EnvironmentSystem_Container_Base.BP_EnvironmentSystem_Container_Base_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_EnvironmentSystem_Container_Base_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Container_Base_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Container_Base.BP_EnvironmentSystem_Container_Base_C.ReplicateEvent
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Container_Base_C::ReplicateEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Container_Base_C", "ReplicateEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Container_Base.BP_EnvironmentSystem_Container_Base_C.SpawnMaterial
// (BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Container_Base_C::SpawnMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Container_Base_C", "SpawnMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Container_Base.BP_EnvironmentSystem_Container_Base_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Container_Base_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Container_Base_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
