#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Container_36

#include "Basic.hpp"

#include "BP_EnvironmentSystem_Container_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EnvironmentSystem_Container_36.BP_EnvironmentSystem_Container_36_C
// 0x0008 (0x03B0 - 0x03A8)
class ABP_EnvironmentSystem_Container_36_C final : public ABP_EnvironmentSystem_Container_Base_C
{
public:
	class UBillboardComponent*                    SpawnPosition1;                                    // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EnvironmentSystem_Container_36_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EnvironmentSystem_Container_36_C")
	}
	static class ABP_EnvironmentSystem_Container_36_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EnvironmentSystem_Container_36_C>();
	}
};
DUMPER7_ASSERTS_ABP_EnvironmentSystem_Container_36_C;

SDK_NAMESPACE_END
