#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Bush

#include "Basic.hpp"

#include "BP_EnvironmentSystem_DamagedSpawn_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EnvironmentSystem_Bush.BP_EnvironmentSystem_Bush_C
// 0x0028 (0x0388 - 0x0360)
class ABP_EnvironmentSystem_Bush_C final : public ABP_EnvironmentSystem_DamagedSpawn_C
{
public:
	uint8                                         Pad_360[0x8];                                      // 0x0360(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UBillboardComponent*                    SpawnPosition4;                                    // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    SpawnPosition3;                                    // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    SpawnPosition2;                                    // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    SpawnPosition1;                                    // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveDestroyed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EnvironmentSystem_Bush_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EnvironmentSystem_Bush_C")
	}
	static class ABP_EnvironmentSystem_Bush_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EnvironmentSystem_Bush_C>();
	}
};
DUMPER7_ASSERTS_ABP_EnvironmentSystem_Bush_C;

SDK_NAMESPACE_END
