#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Ruins

#include "Basic.hpp"

#include "BP_EnvironmentSystem_Ruins_classes.hpp"


SDK_NAMESPACE_START

// Function BP_EnvironmentSystem_Ruins.BP_EnvironmentSystem_Ruins_C.SpawnMaterial
// (BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Ruins_C::SpawnMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Ruins_C", "SpawnMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Ruins.BP_EnvironmentSystem_Ruins_C.ReplicateEvent
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Ruins_C::ReplicateEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Ruins_C", "ReplicateEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Ruins.BP_EnvironmentSystem_Ruins_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_EnvironmentSystem_Ruins_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Ruins_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
