#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Food_Base

#include "Basic.hpp"

#include "BP_Food_Base_classes.hpp"
#include "BP_Food_Base_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Food_Base.BP_Food_Base_C.UseItem
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Food_Base_C::UseItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "UseItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Food_Base.BP_Food_Base_C.DefaultMontagePlay
// (BlueprintCallable, BlueprintEvent)

void ABP_Food_Base_C::DefaultMontagePlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "DefaultMontagePlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Food_Base.BP_Food_Base_C.PickState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_FirstPersonCharacter_Main_C*  Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::PickState(bool State, class ABP_FirstPersonCharacter_Main_C* Character, int32 SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "PickState");

	Params::BP_Food_Base_C_PickState Parms{};

	Parms.State = State;
	Parms.Character = Character;
	Parms.SlotIndex = SlotIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.SetMeshDatas
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    KeepScale                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::SetMeshDatas(bool KeepScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "SetMeshDatas");

	Params::BP_Food_Base_C_SetMeshDatas Parms{};

	Parms.KeepScale = KeepScale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.Shot
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PressState                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  PushTime                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_FirstPersonCharacter_Main_C*  SourcePlayer                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::Shot(bool PressState, double PushTime, class ABP_FirstPersonCharacter_Main_C* SourcePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "Shot");

	Params::BP_Food_Base_C_Shot Parms{};

	Parms.PressState = PressState;
	Parms.PushTime = PushTime;
	Parms.SourcePlayer = SourcePlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Food_Base_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Food_Base.BP_Food_Base_C.Attack_AC_Remote
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TimeRange                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ComponentName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  DamageMultiply                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  StanMultiply                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::Attack_AC_Remote(double TimeRange, class FName ComponentName, double DamageMultiply, double StanMultiply)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "Attack_AC_Remote");

	Params::BP_Food_Base_C_Attack_AC_Remote Parms{};

	Parms.TimeRange = TimeRange;
	Parms.ComponentName = ComponentName;
	Parms.DamageMultiply = DamageMultiply;
	Parms.StanMultiply = StanMultiply;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.Combo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TimeRange                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             ComboName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::Combo(double TimeRange, class FName ComboName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "Combo");

	Params::BP_Food_Base_C_Combo Parms{};

	Parms.TimeRange = TimeRange;
	Parms.ComboName = ComboName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.Attack_AC
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TimeRange                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             AttackName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  DamageMultiply                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    MutipleHitPossible                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  StanMultiply                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::Attack_AC(double TimeRange, class FName AttackName, double DamageMultiply, bool MutipleHitPossible, double StanMultiply)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "Attack_AC");

	Params::BP_Food_Base_C_Attack_AC Parms{};

	Parms.TimeRange = TimeRange;
	Parms.AttackName = AttackName;
	Parms.DamageMultiply = DamageMultiply;
	Parms.MutipleHitPossible = MutipleHitPossible;
	Parms.StanMultiply = StanMultiply;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.CollisionReset
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Food_Base_C::CollisionReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "CollisionReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Food_Base.BP_Food_Base_C.OnCompleted_AB8CFA264FD7DA0BDDFF52A4E41377D1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnCompleted_AB8CFA264FD7DA0BDDFF52A4E41377D1(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnCompleted_AB8CFA264FD7DA0BDDFF52A4E41377D1");

	Params::BP_Food_Base_C_OnCompleted_AB8CFA264FD7DA0BDDFF52A4E41377D1 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnBlendOut_AB8CFA264FD7DA0BDDFF52A4E41377D1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnBlendOut_AB8CFA264FD7DA0BDDFF52A4E41377D1(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnBlendOut_AB8CFA264FD7DA0BDDFF52A4E41377D1");

	Params::BP_Food_Base_C_OnBlendOut_AB8CFA264FD7DA0BDDFF52A4E41377D1 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnInterrupted_AB8CFA264FD7DA0BDDFF52A4E41377D1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnInterrupted_AB8CFA264FD7DA0BDDFF52A4E41377D1(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnInterrupted_AB8CFA264FD7DA0BDDFF52A4E41377D1");

	Params::BP_Food_Base_C_OnInterrupted_AB8CFA264FD7DA0BDDFF52A4E41377D1 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnNotifyBegin_AB8CFA264FD7DA0BDDFF52A4E41377D1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnNotifyBegin_AB8CFA264FD7DA0BDDFF52A4E41377D1(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnNotifyBegin_AB8CFA264FD7DA0BDDFF52A4E41377D1");

	Params::BP_Food_Base_C_OnNotifyBegin_AB8CFA264FD7DA0BDDFF52A4E41377D1 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnNotifyEnd_AB8CFA264FD7DA0BDDFF52A4E41377D1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnNotifyEnd_AB8CFA264FD7DA0BDDFF52A4E41377D1(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnNotifyEnd_AB8CFA264FD7DA0BDDFF52A4E41377D1");

	Params::BP_Food_Base_C_OnNotifyEnd_AB8CFA264FD7DA0BDDFF52A4E41377D1 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnCompleted_1EE8139B44BEF7533BB7DA8825C05C72
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnCompleted_1EE8139B44BEF7533BB7DA8825C05C72(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnCompleted_1EE8139B44BEF7533BB7DA8825C05C72");

	Params::BP_Food_Base_C_OnCompleted_1EE8139B44BEF7533BB7DA8825C05C72 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnBlendOut_1EE8139B44BEF7533BB7DA8825C05C72
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnBlendOut_1EE8139B44BEF7533BB7DA8825C05C72(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnBlendOut_1EE8139B44BEF7533BB7DA8825C05C72");

	Params::BP_Food_Base_C_OnBlendOut_1EE8139B44BEF7533BB7DA8825C05C72 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnInterrupted_1EE8139B44BEF7533BB7DA8825C05C72
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnInterrupted_1EE8139B44BEF7533BB7DA8825C05C72(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnInterrupted_1EE8139B44BEF7533BB7DA8825C05C72");

	Params::BP_Food_Base_C_OnInterrupted_1EE8139B44BEF7533BB7DA8825C05C72 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnNotifyBegin_1EE8139B44BEF7533BB7DA8825C05C72
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnNotifyBegin_1EE8139B44BEF7533BB7DA8825C05C72(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnNotifyBegin_1EE8139B44BEF7533BB7DA8825C05C72");

	Params::BP_Food_Base_C_OnNotifyBegin_1EE8139B44BEF7533BB7DA8825C05C72 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.OnNotifyEnd_1EE8139B44BEF7533BB7DA8825C05C72
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Food_Base_C::OnNotifyEnd_1EE8139B44BEF7533BB7DA8825C05C72(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "OnNotifyEnd_1EE8139B44BEF7533BB7DA8825C05C72");

	Params::BP_Food_Base_C_OnNotifyEnd_1EE8139B44BEF7533BB7DA8825C05C72 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.ApplyDamage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Sweep_Result                                           (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Food_Base_C::ApplyDamage(class UObject* OtherActor, const struct FHitResult& Sweep_Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "ApplyDamage");

	Params::BP_Food_Base_C_ApplyDamage Parms{};

	Parms.OtherActor = OtherActor;
	Parms.Sweep_Result = std::move(Sweep_Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Food_Base.BP_Food_Base_C.IsChangeImage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsInteract                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            OverrideText                                           (Parm, OutParm)

void ABP_Food_Base_C::IsChangeImage(bool* IsInteract, class FText* OverrideText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Food_Base_C", "IsChangeImage");

	Params::BP_Food_Base_C_IsChangeImage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsInteract != nullptr)
		*IsInteract = Parms.IsInteract;

	if (OverrideText != nullptr)
		*OverrideText = std::move(Parms.OverrideText);
}


SDK_NAMESPACE_END
