#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FreezeBodyIce

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "EN_DamageType_structs.hpp"
#include "EN_StanType_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FreezeBodyIce.BP_FreezeBodyIce_C
// 0x0040 (0x02E8 - 0x02A8)
class ABP_FreezeBodyIce_C final : public AActor
{
public:
	uint8                                         Pad_2A8[0x8];                                      // 0x02A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UBPC_LinkCharacterCustomControl_C*      BPC_LinkCharacterCustomControl;                    // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCPP_AC_CustomPhysicsForce*             CPP_AC_CustomPhysicsForce;                         // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Mesh;                                              // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CollisionMesh;                                     // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_LINK_C*        ParentTarget;                                      // 0x02D0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	double                                        FreezeValue;                                       // 0x02D8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BodyIndex;                                         // 0x02E0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void UnZip();
	void StanDamage(EN_StanType StanType);
	void StaminaDamage(double Value);
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveDestroyed();
	void ReceiveBeginPlay();
	void Heat(double Value);
	void GetParryState(bool* State);
	void DamageToPlayerController(class AActor* TargetActor, double DamageValue, int32 TeamIndex, EN_DamageType DamageType, const struct FTransform& SourceAgentPoint, bool UnAvoidable, class FName DamageName, const struct FHitResult& HitRezult, class AActor* SourceActor);
	void Damage(double DamageValue, int32 TeamIndex, EN_DamageType DamageType, const struct FTransform& SourceAgentPoint, bool UnAvoidable, class FName DamageName, class AActor* SourceActor, struct FFinishFilter* Finish);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FreezeBodyIce_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FreezeBodyIce_C")
	}
	static class ABP_FreezeBodyIce_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FreezeBodyIce_C>();
	}
};
DUMPER7_ASSERTS_ABP_FreezeBodyIce_C;

SDK_NAMESPACE_END
