#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Glue_CustomPhysics

#include "Basic.hpp"

#include "BP_Glue_CustomPhysics_classes.hpp"
#include "BP_Glue_CustomPhysics_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.SetLinkComponent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UActorComponent*                  Primitive                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Glue_CustomPhysics_C::SetLinkComponent(class UActorComponent* Primitive, bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "SetLinkComponent");

	Params::BP_Glue_CustomPhysics_C_SetLinkComponent Parms{};

	Parms.Primitive = Primitive;
	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.ResetCustomForce
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Glue_CustomPhysics_C::ResetCustomForce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "ResetCustomForce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Glue_CustomPhysics_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.PrimitiveCheck
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const class UPrimitiveComponent*&       PrimitiveComp                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Glue_CustomPhysics_C::PrimitiveCheck(class AActor* Actor, const class UPrimitiveComponent*& PrimitiveComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "PrimitiveCheck");

	Params::BP_Glue_CustomPhysics_C_PrimitiveCheck Parms{};

	Parms.Actor = Actor;
	Parms.PrimitiveComp = PrimitiveComp;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.LINKCheckFunc
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   StaticLocation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UPrimitiveComponent*&       PrimitiveComp                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void ABP_Glue_CustomPhysics_C::LINKCheckFunc(const struct FVector& StaticLocation, const class UPrimitiveComponent*& PrimitiveComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "LINKCheckFunc");

	Params::BP_Glue_CustomPhysics_C_LINKCheckFunc Parms{};

	Parms.StaticLocation = std::move(StaticLocation);
	Parms.PrimitiveComp = PrimitiveComp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.LINK_Overlap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              PrimitiveComponent                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Glue_CustomPhysics_C::LINK_Overlap(class UPrimitiveComponent* PrimitiveComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "LINK_Overlap");

	Params::BP_Glue_CustomPhysics_C_LINK_Overlap Parms{};

	Parms.PrimitiveComponent = PrimitiveComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.DebugVisualize__UpdateFunc
// (BlueprintEvent)

void ABP_Glue_CustomPhysics_C::DebugVisualize__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "DebugVisualize__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.DebugVisualize__FinishedFunc
// (BlueprintEvent)

void ABP_Glue_CustomPhysics_C::DebugVisualize__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "DebugVisualize__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Glue_CustomPhysics_C::BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature");

	Params::BP_Glue_CustomPhysics_C_BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Glue_CustomPhysics_C::BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_Glue_CustomPhysics_C_BndEvt__BP_Glue_CustomPhysics_GlueArea_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.AddPower
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  power                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           SourceActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Glue_CustomPhysics_C::AddPower(double power, class AActor* SourceActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "AddPower");

	Params::BP_Glue_CustomPhysics_C_AddPower Parms{};

	Parms.power = power;
	Parms.SourceActor = SourceActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.AddCustomRevicePower
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   PowerAmount_AddCustomRevicePower                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Glue_CustomPhysics_C::AddCustomRevicePower(float PowerAmount_AddCustomRevicePower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "AddCustomRevicePower");

	Params::BP_Glue_CustomPhysics_C_AddCustomRevicePower Parms{};

	Parms.PowerAmount_AddCustomRevicePower = PowerAmount_AddCustomRevicePower;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Glue_CustomPhysics.BP_Glue_CustomPhysics_C.AddCustomForce
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  AddValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Glue_CustomPhysics_C::AddCustomForce(double AddValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Glue_CustomPhysics_C", "AddCustomForce");

	Params::BP_Glue_CustomPhysics_C_AddCustomForce Parms{};

	Parms.AddValue = AddValue;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
