#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GizmoVisual

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GizmoVisual.BP_GizmoVisual_C
// 0x0018 (0x02C0 - 0x02A8)
class ABP_GizmoVisual_C final : public AActor
{
public:
	class UStaticMeshComponent*                   GizmoX;                                            // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   GizmoY;                                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void AddRotation(const struct FVector2D& AddValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GizmoVisual_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GizmoVisual_C")
	}
	static class ABP_GizmoVisual_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GizmoVisual_C>();
	}
};
DUMPER7_ASSERTS_ABP_GizmoVisual_C;

SDK_NAMESPACE_END
