#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InstanceCreate_Base

#include "Basic.hpp"

#include "BP_InstanceCreate_Base_classes.hpp"


SDK_NAMESPACE_START

// Function BP_InstanceCreate_Base.BP_InstanceCreate_Base_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_InstanceCreate_Base_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InstanceCreate_Base_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InstanceCreate_Base.BP_InstanceCreate_Base_C.InstancePack
// (BlueprintCallable, BlueprintEvent)

void ABP_InstanceCreate_Base_C::InstancePack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InstanceCreate_Base_C", "InstancePack");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
