#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LinkGoalPosition

#include "Basic.hpp"

#include "BP_LinkGoalPosition_classes.hpp"
#include "BP_LinkGoalPosition_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.ToBlueFlag
// (BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::ToBlueFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "ToBlueFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.SetUsedPoint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsUsed                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::SetUsedPoint(bool IsUsed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "SetUsedPoint");

	Params::BP_LinkGoalPosition_C_SetUsedPoint Parms{};

	Parms.IsUsed = IsUsed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.RespawnCall
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_MiniPenguin_C*                Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::RespawnCall(class ABP_MiniPenguin_C* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "RespawnCall");

	Params::BP_LinkGoalPosition_C_RespawnCall Parms{};

	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.ResetGoalEevent
// (BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::ResetGoalEevent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "ResetGoalEevent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.RegisterLinkPoint
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGuid&                     ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_LinkPoint_C*                  LinkPoint                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::RegisterLinkPoint(const struct FGuid& ID, class ABP_LinkPoint_C* LinkPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "RegisterLinkPoint");

	Params::BP_LinkGoalPosition_C_RegisterLinkPoint Parms{};

	Parms.ID = std::move(ID);
	Parms.LinkPoint = LinkPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LinkGoalPosition_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.MakePole
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UInstancedStaticMeshComponent*    InstancedStaticMeshComp                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::MakePole(class UInstancedStaticMeshComponent* InstancedStaticMeshComp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "MakePole");

	Params::BP_LinkGoalPosition_C_MakePole Parms{};

	Parms.InstancedStaticMeshComp = InstancedStaticMeshComp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.LINK_FragReActivate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsLastLink                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::LINK_FragReActivate(bool IsLastLink)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "LINK_FragReActivate");

	Params::BP_LinkGoalPosition_C_LINK_FragReActivate Parms{};

	Parms.IsLastLink = IsLastLink;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.LastTargetActivate
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ActivateState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::LastTargetActivate(bool ActivateState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "LastTargetActivate");

	Params::BP_LinkGoalPosition_C_LastTargetActivate Parms{};

	Parms.ActivateState = ActivateState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.LastLink
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::LastLink()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "LastLink");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.IsChangeImage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsInteract                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            OverrideText                                           (Parm, OutParm)

void ABP_LinkGoalPosition_C::IsChangeImage(bool* IsInteract, class FText* OverrideText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "IsChangeImage");

	Params::BP_LinkGoalPosition_C_IsChangeImage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsInteract != nullptr)
		*IsInteract = Parms.IsInteract;

	if (OverrideText != nullptr)
		*OverrideText = std::move(Parms.OverrideText);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.InteractSignal
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::InteractSignal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "InteractSignal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.GoalEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::GoalEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "GoalEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.GetDuplicateValues
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FGuid>*                   DuplicateValues                                        (Parm, OutParm)

void ABP_LinkGoalPosition_C::GetDuplicateValues(TArray<struct FGuid>* DuplicateValues)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "GetDuplicateValues");

	Params::BP_LinkGoalPosition_C_GetDuplicateValues Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DuplicateValues != nullptr)
		*DuplicateValues = std::move(Parms.DuplicateValues);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.FragVisualUpdate
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsUsed                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::FragVisualUpdate(bool IsUsed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "FragVisualUpdate");

	Params::BP_LinkGoalPosition_C_FragVisualUpdate Parms{};

	Parms.IsUsed = IsUsed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.CanInteract
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_LinkGoalPosition_C::CanInteract()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "CanInteract");

	Params::BP_LinkGoalPosition_C_CanInteract Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.BPI_InteractStart(Server)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  First_Person                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::BPI_InteractStart_Server_(class ABP_FirstPersonCharacter_Main_C* First_Person)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "BPI_InteractStart(Server)");

	Params::BP_LinkGoalPosition_C_BPI_InteractStart_Server_ Parms{};

	Parms.First_Person = First_Person;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.BPI_InteractStart(Local)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  First_Person                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::BPI_InteractStart_Local_(class ABP_FirstPersonCharacter_Main_C* First_Person)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "BPI_InteractStart(Local)");

	Params::BP_LinkGoalPosition_C_BPI_InteractStart_Local_ Parms{};

	Parms.First_Person = First_Person;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.BPI_InteractStart
// (BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  First_Person                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::BPI_InteractStart(class ABP_FirstPersonCharacter_Main_C* First_Person)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "BPI_InteractStart");

	Params::BP_LinkGoalPosition_C_BPI_InteractStart Parms{};

	Parms.First_Person = First_Person;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.BPI_InteractEnd
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_LinkGoalPosition_C::BPI_InteractEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "BPI_InteractEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LinkGoalPosition_C::BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_LinkGoalPosition_C_BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LinkGoalPosition.BP_LinkGoalPosition_C.BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_LinkGoalPosition_C::BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LinkGoalPosition_C", "BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_LinkGoalPosition_C_BndEvt__BP_LinkGoalPosition_LinkFlagOverlapZone_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
