#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LINK_Manequin

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LINK_Manequin.BP_LINK_Manequin_C
// 0x0020 (0x02C8 - 0x02A8)
class ABP_LINK_Manequin_C final : public AActor
{
public:
	uint8                                         Pad_2A8[0x8];                                      // 0x02A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UBPC_LinkCharacterCustomControl_C*      BPC_LinkCharacterCustomControl;                    // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         PlayerIndex;                                       // 0x02C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LINK_Manequin_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LINK_Manequin_C")
	}
	static class ABP_LINK_Manequin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LINK_Manequin_C>();
	}
};
DUMPER7_ASSERTS_ABP_LINK_Manequin_C;

SDK_NAMESPACE_END
