#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MagicHandGrabArea

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MagicHandGrabArea.BP_MagicHandGrabArea_C
// 0x0008 (0x02B0 - 0x02A8)
class ABP_MagicHandGrabArea_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Sphere;                                            // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MagicHandGrabArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MagicHandGrabArea_C")
	}
	static class ABP_MagicHandGrabArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MagicHandGrabArea_C>();
	}
};
DUMPER7_ASSERTS_ABP_MagicHandGrabArea_C;

SDK_NAMESPACE_END
