#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RandomObject_RandomMesh

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "BP_RandomObject_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RandomObject_RandomMesh.BP_RandomObject_RandomMesh_C
// 0x0030 (0x02E8 - 0x02B8)
class ABP_RandomObject_RandomMesh_C final : public ABP_RandomObject_Base_C
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         TargetActors;                                      // 0x02C0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	TArray<class UStaticMesh*>                    RandomMesh;                                        // 0x02D0(0x0010)(Edit, BlueprintVisible)
	struct FRandomStream                          Seed;                                              // 0x02E0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, RepNotify, NoDestructor)

public:
	void CheckLoop();
	void IndexUpdate();
	void OnRep_CurrentIndex();
	void OnRep_Seed();
	void ReceiveBeginPlay();
	void SetIndex(bool* Error);
	void SpawnSet();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RandomObject_RandomMesh_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RandomObject_RandomMesh_C")
	}
	static class ABP_RandomObject_RandomMesh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RandomObject_RandomMesh_C>();
	}
};
DUMPER7_ASSERTS_ABP_RandomObject_RandomMesh_C;

SDK_NAMESPACE_END
