#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Structure_Ice

#include "Basic.hpp"

#include "BP_Structure_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Structure_Ice.BP_Structure_Ice_C
// 0x0020 (0x02E0 - 0x02C0)
class ABP_Structure_Ice_C final : public ABP_Structure_Base_C
{
public:
	uint8                                         Pad_2C0[0x8];                                      // 0x02C0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UStaticMesh*>                    RandomMesh;                                        // 0x02D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ReceiveBeginPlay();
	void Generate();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Structure_Ice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Structure_Ice_C")
	}
	static class ABP_Structure_Ice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Structure_Ice_C>();
	}
};
DUMPER7_ASSERTS_ABP_Structure_Ice_C;

SDK_NAMESPACE_END
