#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Simple_VAT_Player_PBR

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Simple_VAT_Player_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Simple_VAT_Player_PBR.BP_Simple_VAT_Player_PBR_C
// 0x0040 (0x02F8 - 0x02B8)
class ABP_Simple_VAT_Player_PBR_C final : public ABP_Simple_VAT_Player_Base_C
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BaseTime_Time_883ADD2A4DE64EC7552965BB86FB0D92;    // 0x02C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            BaseTime__Direction_883ADD2A4DE64EC7552965BB86FB0D92; // 0x02C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C5[0x3];                                      // 0x02C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     BaseTime;                                          // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UBP_RBD_VAT_DataAssets_C> VATDataAsset;                                     // 0x02D0(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void OnLoaded_F3F51E7A482D22D54F2E9A9B92C6E184(class UObject* Loaded);
	void BaseTime__UpdateFunc();
	void BaseTime__FinishedFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Simple_VAT_Player_PBR_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Simple_VAT_Player_PBR_C")
	}
	static class ABP_Simple_VAT_Player_PBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Simple_VAT_Player_PBR_C>();
	}
};
DUMPER7_ASSERTS_ABP_Simple_VAT_Player_PBR_C;

SDK_NAMESPACE_END
