#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_TaskObject_FindAndTakeHomeGiftBox

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPC_TaskObject_FindAndTakeHomeGiftBox.BPC_TaskObject_FindAndTakeHomeGiftBox_C.GoalActor
// 0x0008 (0x0008 - 0x0000)
struct BPC_TaskObject_FindAndTakeHomeGiftBox_C_GoalActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_TaskObject_FindAndTakeHomeGiftBox_C_GoalActor;

// Function BPC_TaskObject_FindAndTakeHomeGiftBox.BPC_TaskObject_FindAndTakeHomeGiftBox_C.GeneratedActor
// 0x0008 (0x0008 - 0x0000)
struct BPC_TaskObject_FindAndTakeHomeGiftBox_C_GeneratedActor final
{
public:
	class AActor*                                 GeneratedActor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_TaskObject_FindAndTakeHomeGiftBox_C_GeneratedActor;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
