#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_TaskObject_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPC_TaskObject_Base.BPC_TaskObject_Base_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BPC_TaskObject_Base_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_TaskObject_Base_C_ReceiveEndPlay;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
