#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_PhysicsNetDormancyControl

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_PhysicsNetDormancyControl.BPC_PhysicsNetDormancyControl_C
// 0x0008 (0x00C0 - 0x00B8)
class UBPC_PhysicsNetDormancyControl_C final : public UActorComponent
{
public:
	uint8                                         Pad_B8[0x8];                                       // 0x00B8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Wake(class UPrimitiveComponent* WakingComponent, class FName BoneName);
	void SleepCall();
	void Sleep(class UPrimitiveComponent* SleepingComponent, class FName BoneName);
	void SimulatePhysicsCheck();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_PhysicsNetDormancyControl_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_PhysicsNetDormancyControl_C")
	}
	static class UBPC_PhysicsNetDormancyControl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_PhysicsNetDormancyControl_C>();
	}
};
DUMPER7_ASSERTS_UBPC_PhysicsNetDormancyControl_C;

SDK_NAMESPACE_END
