#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_PhysicsNetDormancyControl

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPC_PhysicsNetDormancyControl.BPC_PhysicsNetDormancyControl_C.Wake
// 0x0010 (0x0010 - 0x0000)
struct BPC_PhysicsNetDormancyControl_C_Wake final
{
public:
	class UPrimitiveComponent*                    WakingComponent;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   BoneName;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_PhysicsNetDormancyControl_C_Wake;

// Function BPC_PhysicsNetDormancyControl.BPC_PhysicsNetDormancyControl_C.Sleep
// 0x0010 (0x0010 - 0x0000)
struct BPC_PhysicsNetDormancyControl_C_Sleep final
{
public:
	class UPrimitiveComponent*                    SleepingComponent;                                 // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   BoneName;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_PhysicsNetDormancyControl_C_Sleep;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
