#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_InventoryController

#include "Basic.hpp"

#include "BPC_InventoryController_classes.hpp"
#include "BPC_InventoryController_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_InventoryController.BPC_InventoryController_C.DropCall(Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ForceNoDrop                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::DropCall_Server_(int32 SlotIndex, bool ForceNoDrop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "DropCall(Server)");

	Params::BPC_InventoryController_C_DropCall_Server_ Parms{};

	Parms.SlotIndex = SlotIndex;
	Parms.ForceNoDrop = ForceNoDrop;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.DropCall(Local)
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ForceNoDrop                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::DropCall_Local_(bool ForceNoDrop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "DropCall(Local)");

	Params::BPC_InventoryController_C_DropCall_Local_ Parms{};

	Parms.ForceNoDrop = ForceNoDrop;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.HaveItemSync(StackCount)
// (BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::HaveItemSync_StackCount_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "HaveItemSync(StackCount)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.UpdateCurrentCoreData(Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ItemCoreDatas&         Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBPC_InventoryController_C::UpdateCurrentCoreData_Server_(const struct FST_ItemCoreDatas& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "UpdateCurrentCoreData(Server)");

	Params::BPC_InventoryController_C_UpdateCurrentCoreData_Server_ Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.HaveItemSync
// (BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::HaveItemSync()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "HaveItemSync");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBPC_InventoryController_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.GetItemData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ItemName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Rezult                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FCPP_GameItemData*               ItemData                                               (Parm, OutParm)

void UBPC_InventoryController_C::GetItemData(class FName ItemName, bool* Rezult, struct FCPP_GameItemData* ItemData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "GetItemData");

	Params::BPC_InventoryController_C_GetItemData Parms{};

	Parms.ItemName = ItemName;

	UObject::ProcessEvent(Func, &Parms);

	if (Rezult != nullptr)
		*Rezult = Parms.Rezult;

	if (ItemData != nullptr)
		*ItemData = std::move(Parms.ItemData);
}


// Function BPC_InventoryController.BPC_InventoryController_C.GetCurrentSlotItem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            ItemName                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FST_ItemCoreDatas*               CoreDatas                                              (Parm, OutParm, HasGetValueTypeHash)

void UBPC_InventoryController_C::GetCurrentSlotItem(class FName* ItemName, struct FST_ItemCoreDatas* CoreDatas)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "GetCurrentSlotItem");

	Params::BPC_InventoryController_C_GetCurrentSlotItem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ItemName != nullptr)
		*ItemName = Parms.ItemName;

	if (CoreDatas != nullptr)
		*CoreDatas = std::move(Parms.CoreDatas);
}


// Function BPC_InventoryController.BPC_InventoryController_C.SlotUpdate
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::SlotUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "SlotUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.SlotChange
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MoveValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  CurrentIndex                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::SlotChange(int32 MoveValue, int32* CurrentIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "SlotChange");

	Params::BPC_InventoryController_C_SlotChange Parms{};

	Parms.MoveValue = MoveValue;

	UObject::ProcessEvent(Func, &Parms);

	if (CurrentIndex != nullptr)
		*CurrentIndex = Parms.CurrentIndex;
}


// Function BPC_InventoryController.BPC_InventoryController_C.SetSlotValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MoveValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::SetSlotValue(int32 MoveValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "SetSlotValue");

	Params::BPC_InventoryController_C_SetSlotValue Parms{};

	Parms.MoveValue = MoveValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.OnRep_CurrentSlotIndex
// (BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::OnRep_CurrentSlotIndex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "OnRep_CurrentSlotIndex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.AddInventory
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FST_ItemCoreDatas&         CoreDatas                                              (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool*                                   Rezult                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::AddInventory(int32 SlotIndex, const struct FST_ItemCoreDatas& CoreDatas, bool* Rezult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "AddInventory");

	Params::BPC_InventoryController_C_AddInventory Parms{};

	Parms.SlotIndex = SlotIndex;
	Parms.CoreDatas = std::move(CoreDatas);

	UObject::ProcessEvent(Func, &Parms);

	if (Rezult != nullptr)
		*Rezult = Parms.Rezult;
}


// Function BPC_InventoryController.BPC_InventoryController_C.GetKeyNames
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FName>*                    KeyNames                                               (Parm, OutParm)

void UBPC_InventoryController_C::GetKeyNames(TArray<class FName>* KeyNames)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "GetKeyNames");

	Params::BPC_InventoryController_C_GetKeyNames Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (KeyNames != nullptr)
		*KeyNames = std::move(Parms.KeyNames);
}


// Function BPC_InventoryController.BPC_InventoryController_C.CopyVariable
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBPC_InventoryController_C*       Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::CopyVariable(class UBPC_InventoryController_C* Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "CopyVariable");

	Params::BPC_InventoryController_C_CopyVariable Parms{};

	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.OnRep_ItemCoreDatas
// (BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::OnRep_ItemCoreDatas()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "OnRep_ItemCoreDatas");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.UpdateCurrentCoreData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ItemCoreDatas&         Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBPC_InventoryController_C::UpdateCurrentCoreData(const struct FST_ItemCoreDatas& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "UpdateCurrentCoreData");

	Params::BPC_InventoryController_C_UpdateCurrentCoreData Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.DropItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   OverrideDropLocation                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ForceNoDrop                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    MultiAllDrop                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsDrop                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::DropItem(int32 SlotIndex, const struct FVector& OverrideDropLocation, bool ForceNoDrop, bool MultiAllDrop, bool* IsDrop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "DropItem");

	Params::BPC_InventoryController_C_DropItem Parms{};

	Parms.SlotIndex = SlotIndex;
	Parms.OverrideDropLocation = std::move(OverrideDropLocation);
	Parms.ForceNoDrop = ForceNoDrop;
	Parms.MultiAllDrop = MultiAllDrop;

	UObject::ProcessEvent(Func, &Parms);

	if (IsDrop != nullptr)
		*IsDrop = Parms.IsDrop;
}


// Function BPC_InventoryController.BPC_InventoryController_C.GetEmptySlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  SlotIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::GetEmptySlot(int32* SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "GetEmptySlot");

	Params::BPC_InventoryController_C_GetEmptySlot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SlotIndex != nullptr)
		*SlotIndex = Parms.SlotIndex;
}


// Function BPC_InventoryController.BPC_InventoryController_C.SlotIsEmpty
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBPC_InventoryController_C::SlotIsEmpty(int32 SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "SlotIsEmpty");

	Params::BPC_InventoryController_C_SlotIsEmpty Parms{};

	Parms.SlotIndex = SlotIndex;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BPC_InventoryController.BPC_InventoryController_C.RespawnItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ItemClass                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FST_ItemCoreDatas&         ItemCoreDatas                                          (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// const struct FVector&                   OverrideDropLocation                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  Rotaiton                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBPC_InventoryController_C::RespawnItem(class UClass* ItemClass, const struct FST_ItemCoreDatas& ItemCoreDatas, const struct FVector& OverrideDropLocation, const struct FRotator& Rotaiton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "RespawnItem");

	Params::BPC_InventoryController_C_RespawnItem Parms{};

	Parms.ItemClass = ItemClass;
	Parms.ItemCoreDatas = std::move(ItemCoreDatas);
	Parms.OverrideDropLocation = std::move(OverrideDropLocation);
	Parms.Rotaiton = std::move(Rotaiton);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.ClearSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::ClearSlot(int32 SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "ClearSlot");

	Params::BPC_InventoryController_C_ClearSlot Parms{};

	Parms.SlotIndex = SlotIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.ClearAllItems
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::ClearAllItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "ClearAllItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.SlotCanStack
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FST_ItemCoreDatas&         ST_ItemCoreDatas                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBPC_InventoryController_C::SlotCanStack(int32 SlotIndex, const struct FST_ItemCoreDatas& ST_ItemCoreDatas)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "SlotCanStack");

	Params::BPC_InventoryController_C_SlotCanStack Parms{};

	Parms.SlotIndex = SlotIndex;
	Parms.ST_ItemCoreDatas = std::move(ST_ItemCoreDatas);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BPC_InventoryController.BPC_InventoryController_C.GetCanStackSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ItemCoreDatas&         ST_ItemCoreDatas                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// int32*                                  SlotIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::GetCanStackSlot(const struct FST_ItemCoreDatas& ST_ItemCoreDatas, int32* SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "GetCanStackSlot");

	Params::BPC_InventoryController_C_GetCanStackSlot Parms{};

	Parms.ST_ItemCoreDatas = std::move(ST_ItemCoreDatas);

	UObject::ProcessEvent(Func, &Parms);

	if (SlotIndex != nullptr)
		*SlotIndex = Parms.SlotIndex;
}


// Function BPC_InventoryController.BPC_InventoryController_C.OnRep_StackState
// (BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::OnRep_StackState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "OnRep_StackState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_InventoryController.BPC_InventoryController_C.AddCoreOption
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FName&                      Key                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_InventoryController_C::AddCoreOption(int32 Index_0, const class FName& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "AddCoreOption");

	Params::BPC_InventoryController_C_AddCoreOption Parms{};

	Parms.Index_0 = Index_0;
	Parms.Key = Key;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_InventoryController.BPC_InventoryController_C.CleanCheckAllSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBPC_InventoryController_C::CleanCheckAllSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_InventoryController_C", "CleanCheckAllSlot");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
