#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_ItemReplicateController_Magnet

#include "Basic.hpp"

#include "BPC_ItemReplicateController_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C
// 0x0010 (0x00F0 - 0x00E0)
class UBPC_ItemReplicateController_Magnet_C final : public UBPC_ItemReplicateController_Base_C
{
public:
	uint8                                         Pad_E0[0x8];                                       // 0x00E0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    AddForceTarget;                                    // 0x00E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void UseItem_Server_(bool State_UseItem_Server_);
	void UseItem_Replicate_(bool State_UseItem_Replicate_);
	void UseItem_Local_(bool State_UseItem_Local_);
	void SetForceTarget(class UPrimitiveComponent* AddForceTarget);
	void ReceiveTick(float DeltaSeconds_ReceiveTick);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_ItemReplicateController_Magnet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_ItemReplicateController_Magnet_C")
	}
	static class UBPC_ItemReplicateController_Magnet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_ItemReplicateController_Magnet_C>();
	}
};
DUMPER7_ASSERTS_UBPC_ItemReplicateController_Magnet_C;

SDK_NAMESPACE_END
