#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_NearInteract

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPC_NearInteract.BPC_NearInteract_C.SetCheckState
// 0x0001 (0x0001 - 0x0000)
struct BPC_NearInteract_C_SetCheckState final
{
public:
	bool                                          State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_NearInteract_C_SetCheckState;

// Function BPC_NearInteract.BPC_NearInteract_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BPC_NearInteract_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds_ReceiveTick;                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_NearInteract_C_ReceiveTick;

// Function BPC_NearInteract.BPC_NearInteract_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BPC_NearInteract_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason_ReceiveEndPlay;                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_NearInteract_C_ReceiveEndPlay;

// Function BPC_NearInteract.BPC_NearInteract_C.GetSelectActor
// 0x0008 (0x0008 - 0x0000)
struct BPC_NearInteract_C_GetSelectActor final
{
public:
	class AActor*                                 CurrentSelectActor;                                // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_NearInteract_C_GetSelectActor;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
