#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPF_Link_Online

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "Mover_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPF_Link_Online.BPF_Link_Online_C
// 0x0000 (0x0028 - 0x0028)
class UBPF_Link_Online_C final : public UBlueprintFunctionLibrary
{
public:
	static void MakeOptionMap(TArray<struct FST_SessionOptionString>& SessionOptions, class UObject* __WorldContext, TMap<class FName, struct FSessionSearchParamBP>* SearchParams);
	static class FString HashStringPure(const class FString& Source, class UObject* __WorldContext);
	static void AddImpulseForce(const struct FVector& Velocity, class AActor* TargetActor, bool VelChange, bool CanForceLocal, class UObject* __WorldContext);
	static void GetSphereDamageInfo(class AActor* HitActor, const struct FVector& hitpoint, class USphereComponent* SphereCollision, class UObject* __WorldContext, double* NormalizedDistanceValue, bool* LineTraceRezult, struct FVector* Velocity);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPF_Link_Online_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPF_Link_Online_C")
	}
	static class UBPF_Link_Online_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPF_Link_Online_C>();
	}
};
DUMPER7_ASSERTS_UBPF_Link_Online_C;

SDK_NAMESPACE_END
