#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ParamaterControl

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_ParamaterControl.BPI_ParamaterControl_C.ChangeParamater(flaot)
// 0x0010 (0x0010 - 0x0000)
struct BPI_ParamaterControl_C_ChangeParamater_flaot_ final
{
public:
	class FName                                   Name_0;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Value;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_ParamaterControl_C_ChangeParamater_flaot_;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
