#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Spectate

#include "Basic.hpp"

#include "BPI_Spectate_classes.hpp"
#include "BPI_Spectate_parameters.hpp"


SDK_NAMESPACE_START

// Function BPI_Spectate.BPI_Spectate_C.ViewChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  SourcePlayer                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Spectate_C::ViewChange(class ABP_FirstPersonCharacter_Main_C* SourcePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_Spectate_C", "ViewChange");

	Params::BPI_Spectate_C_ViewChange Parms{};

	Parms.SourcePlayer = SourcePlayer;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_Spectate.BPI_Spectate_C.SetupSpectateNameplate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_Main_C*  Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Spectate_C::SetupSpectateNameplate(class ABP_FirstPersonCharacter_Main_C* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_Spectate_C", "SetupSpectateNameplate");

	Params::BPI_Spectate_C_SetupSpectateNameplate Parms{};

	Parms.Character = Character;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_Spectate.BPI_Spectate_C.GetCustomPlayerName
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          playerName                                             (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void IBPI_Spectate_C::GetCustomPlayerName(class FString* playerName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_Spectate_C", "GetCustomPlayerName");

	Params::BPI_Spectate_C_GetCustomPlayerName Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (playerName != nullptr)
		*playerName = std::move(Parms.playerName);
}


SDK_NAMESPACE_END
