#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_UI_Basic

#include "Basic.hpp"

#include "BPI_UI_Basic_classes.hpp"
#include "BPI_UI_Basic_parameters.hpp"


SDK_NAMESPACE_START

// Function BPI_UI_Basic.BPI_UI_Basic_C.PlayAnimationMessage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsForward                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_UI_Basic_C::PlayAnimationMessage(bool IsForward, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UI_Basic_C", "PlayAnimationMessage");

	Params::BPI_UI_Basic_C_PlayAnimationMessage Parms{};

	Parms.IsForward = IsForward;
	Parms.Index_0 = Index_0;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_UI_Basic.BPI_UI_Basic_C.SetColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_UI_Basic_C::SetColor(const struct FLinearColor& Color, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UI_Basic_C", "SetColor");

	Params::BPI_UI_Basic_C_SetColor Parms{};

	Parms.Color = std::move(Color);
	Parms.Index_0 = Index_0;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_UI_Basic.BPI_UI_Basic_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_UI_Basic_C::SetText(const class FText& Text, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UI_Basic_C", "SetText");

	Params::BPI_UI_Basic_C_SetText Parms{};

	Parms.Text = std::move(Text);
	Parms.Index_0 = Index_0;

	AsUObject()->ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
