#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_UI_Basic

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_UI_Basic.BPI_UI_Basic_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_UI_Basic_C final
{
public:
	void PlayAnimationMessage(bool IsForward, int32 Index_0);
	void SetColor(const struct FLinearColor& Color, int32 Index_0);
	void SetText(const class FText& Text, int32 Index_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_UI_Basic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_UI_Basic_C")
	}
	static class IBPI_UI_Basic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_UI_Basic_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_UI_Basic_C;

SDK_NAMESPACE_END
