#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_GameConfig

#include "Basic.hpp"

#include "BPI_GameConfig_classes.hpp"


SDK_NAMESPACE_START

// Function BPI_GameConfig.BPI_GameConfig_C.ApplySetting
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_GameConfig_C::ApplySetting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_GameConfig_C", "ApplySetting");

	AsUObject()->ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
