#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CentorIconActor

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_CentorIconActor.BPI_CentorIconActor_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_CentorIconActor_C final
{
public:
	void IsChangeImage(bool* IsInteract, class FText* OverrideText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_CentorIconActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_CentorIconActor_C")
	}
	static class IBPI_CentorIconActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_CentorIconActor_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_CentorIconActor_C;

SDK_NAMESPACE_END
