#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_cLeon

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_cLeon.BPI_cLeon_C.cLeonGetPlayerState
// 0x0008 (0x0008 - 0x0000)
struct BPI_cLeon_C_cLeonGetPlayerState final
{
public:
	class ABP_FirstPersonPlayerState_Online_cLeon_C* PlayerState;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_cLeon_C_cLeonGetPlayerState;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
