#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Spectate

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_Spectate.BPI_Spectate_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Spectate_C final
{
public:
	void ViewChange(class ABP_FirstPersonCharacter_Main_C* SourcePlayer);
	void SetupSpectateNameplate(class ABP_FirstPersonCharacter_Main_C* Character);
	void GetCustomPlayerName(class FString* playerName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_Spectate_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_Spectate_C")
	}
	static class IBPI_Spectate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Spectate_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_Spectate_C;

SDK_NAMESPACE_END
