#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ItemInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "ENUM_HandType_structs.hpp"
#include "ENUM_ClassType_structs.hpp"
#include "ENUM_ItemBindType_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_ItemInterface.BPI_ItemInterface_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_ItemInterface_C final
{
public:
	void UpdateCoreDatas(const struct FST_ItemCoreDatas& CoreDatas);
	void SetMeshDatas(bool KeepScale);
	void PickState(bool State, class ABP_FirstPersonCharacter_Main_C* Character, int32 SlotIndex);
	void InteractItem();
	void GetParentCharacter(class ABP_FirstPersonCharacter_Main_C** FirstpersonCharacter);
	void GetItemInfo(ENUM_HandType* HandType, ENUM_ClassType* ClassType, bool* NotPickUp, struct FRotator* HaveRotation, struct FVector* Add_Position, bool* IsBoneAttach, ENUM_ItemBindType* BindType, class FName* BoneName, struct FST_ItemCoreDatas* CoreDatas);
	void DropItem(const struct FVector& Force_Vector, const struct FVector& CentorPosition);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_ItemInterface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_ItemInterface_C")
	}
	static class IBPI_ItemInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_ItemInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_ItemInterface_C;

SDK_NAMESPACE_END
