#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ParamaterControl

#include "Basic.hpp"

#include "BPI_ParamaterControl_classes.hpp"
#include "BPI_ParamaterControl_parameters.hpp"


SDK_NAMESPACE_START

// Function BPI_ParamaterControl.BPI_ParamaterControl_C.ChangeParamater(flaot)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_ParamaterControl_C::ChangeParamater_flaot_(class FName Name_0, double Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_ParamaterControl_C", "ChangeParamater(flaot)");

	Params::BPI_ParamaterControl_C_ChangeParamater_flaot_ Parms{};

	Parms.Name_0 = Name_0;
	Parms.Value = Value;

	AsUObject()->ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
