#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_MapGenerate

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_MapGenerate.BPI_MapGenerate_C.Generate
// 0x000C (0x000C - 0x0000)
struct BPI_MapGenerate_C_Generate final
{
public:
	struct FRandomStream                          Seed;                                              // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
	int32                                         DepthIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_MapGenerate_C_Generate;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
