#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CopyVAT_Animation

#include "Basic.hpp"

#include "ST_VAT_Datas_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CopyVAT_Animation.CopyVAT_Animation_C.AnimationStart
// 0x0018 (0x0018 - 0x0000)
struct CopyVAT_Animation_C_AnimationStart final
{
public:
	class UStaticMeshComponent*                   ToComponent;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FST_VAT_Datas                          VAT_Datas;                                         // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CopyVAT_Animation_C_AnimationStart;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
