#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CPP_AC_CustomPhysicsForce_2Leg

#include "Basic.hpp"

#include "PenguinHotel_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CPP_AC_CustomPhysicsForce_2Leg.CPP_AC_CustomPhysicsForce_2Leg_C
// 0x0020 (0x0268 - 0x0248)
class UCPP_AC_CustomPhysicsForce_2Leg_C final : public UCPP_AC_CustomPhysicsForce
{
public:
	uint8                                         Pad_248[0x8];                                      // 0x0248(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UCapsuleComponent*                      BaseCapsule;                                       // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        Weight;                                            // 0x0258(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      HitPhysMat;                                        // 0x0260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void SweepCheck();
	void SetTouchPointDatas();
	TMap<class UPrimitiveComponent*, struct FVector> ResetHitPointDatas();
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CPP_AC_CustomPhysicsForce_2Leg_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CPP_AC_CustomPhysicsForce_2Leg_C")
	}
	static class UCPP_AC_CustomPhysicsForce_2Leg_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCPP_AC_CustomPhysicsForce_2Leg_C>();
	}
};
DUMPER7_ASSERTS_UCPP_AC_CustomPhysicsForce_2Leg_C;

SDK_NAMESPACE_END
