#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN_StanType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum EN_StanType.EN_StanType
// NumValues: 0x0004
enum class EN_StanType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	EN_MAX                                   = 3,
};

SDK_NAMESPACE_END
