#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_TouchMiniPenguin

#include "Basic.hpp"

#include "MovieScene_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_3
// 0x0020 (0x0020 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_3 final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	struct FMovieSceneDynamicBindingResolveResult CallFunc_RightItemPositon_DynamicBinding_ReturnValue; // 0x0010(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_3;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_2
// 0x0020 (0x0020 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_2 final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	struct FMovieSceneDynamicBindingResolveResult CallFunc_HeadPosition_DynamicBinding_ReturnValue;  // 0x0010(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_2;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_1
// 0x0020 (0x0020 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_1 final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	struct FMovieSceneDynamicBindingResolveResult CallFunc_LeftItemPositon_DynamicBinding_ReturnValue; // 0x0010(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_1;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_0
// 0x0008 (0x0008 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_0 final
{
public:
	class ABP_FirstPersonCharacter_Main_C*        BP_FirstPersonCharacter;                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_0;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP
// 0x0008 (0x0008 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP final
{
public:
	class ABP_AI_Base_C*                          BP_AI_Base;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.RightItemPositon_DynamicBinding
// 0x0038 (0x0038 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_RightItemPositon_DynamicBinding final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_Main_C*        K2Node_DynamicCast_AsBP_First_Person_Character_Main; // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneDynamicBindingResolveResult K2Node_MakeStruct_MovieSceneDynamicBindingResolveResult; // 0x0028(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_RightItemPositon_DynamicBinding;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.LeftItemPositon_DynamicBinding
// 0x0038 (0x0038 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_LeftItemPositon_DynamicBinding final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_Main_C*        K2Node_DynamicCast_AsBP_First_Person_Character_Main; // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneDynamicBindingResolveResult K2Node_MakeStruct_MovieSceneDynamicBindingResolveResult; // 0x0028(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_LeftItemPositon_DynamicBinding;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.HeadPosition_DynamicBinding
// 0x0038 (0x0038 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_HeadPosition_DynamicBinding final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_Main_C*        K2Node_DynamicCast_AsBP_First_Person_Character_Main; // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneDynamicBindingResolveResult K2Node_MakeStruct_MovieSceneDynamicBindingResolveResult; // 0x0028(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_HeadPosition_DynamicBinding;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.BP_FirstPersonCharacter_Event
// 0x0008 (0x0008 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_BP_FirstPersonCharacter_Event final
{
public:
	class ABP_FirstPersonCharacter_Main_C*        BP_FirstPersonCharacter;                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_BP_FirstPersonCharacter_Event;

// Function LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C.BP_AI_Base_Event
// 0x0008 (0x0008 - 0x0000)
struct LS_TouchMiniPenguin_DirectorBP_C_BP_AI_Base_Event final
{
public:
	class ABP_AI_Base_C*                          BP_AI_Base;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_TouchMiniPenguin_DirectorBP_C_BP_AI_Base_Event;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
