#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RedpointEOSVoiceChat

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "AudioExtensions_classes.hpp"
#include "RedpointEOSVoiceChat_structs.hpp"


SDK_NAMESPACE_START

// Class RedpointEOSVoiceChat.RedpointCompressAudioTestFilesCommandlet
// 0x0000 (0x0080 - 0x0080)
class URedpointCompressAudioTestFilesCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RedpointCompressAudioTestFilesCommandlet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RedpointCompressAudioTestFilesCommandlet")
	}
	static class URedpointCompressAudioTestFilesCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<URedpointCompressAudioTestFilesCommandlet>();
	}
};
DUMPER7_ASSERTS_URedpointCompressAudioTestFilesCommandlet;

// Class RedpointEOSVoiceChat.RedpointHardwareDeviceIdExternalEndpointSettings
// 0x0020 (0x0048 - 0x0028)
class URedpointHardwareDeviceIdExternalEndpointSettings final : public UAudioEndpointSettingsBase
{
public:
	uint8                                         Pad_28[0x20];                                      // 0x0028(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RedpointHardwareDeviceIdExternalEndpointSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RedpointHardwareDeviceIdExternalEndpointSettings")
	}
	static class URedpointHardwareDeviceIdExternalEndpointSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<URedpointHardwareDeviceIdExternalEndpointSettings>();
	}
};
DUMPER7_ASSERTS_URedpointHardwareDeviceIdExternalEndpointSettings;

// Class RedpointEOSVoiceChat.RedpointOutputSoundEffectSubmixPreset
// 0x0108 (0x0170 - 0x0068)
class URedpointOutputSoundEffectSubmixPreset final : public USoundEffectSubmixPreset
{
public:
	uint8                                         Pad_68[0x98];                                      // 0x0068(0x0098)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRedpointOutputSoundEffectSubmixSettings Settings;                                        // 0x0100(0x0070)(NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RedpointOutputSoundEffectSubmixPreset")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RedpointOutputSoundEffectSubmixPreset")
	}
	static class URedpointOutputSoundEffectSubmixPreset* GetDefaultObj()
	{
		return GetDefaultObjImpl<URedpointOutputSoundEffectSubmixPreset>();
	}
};
DUMPER7_ASSERTS_URedpointOutputSoundEffectSubmixPreset;

// Class RedpointEOSVoiceChat.RedpointSoundSubmix
// 0x0000 (0x0248 - 0x0248)
class URedpointSoundSubmix final : public USoundSubmix
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RedpointSoundSubmix")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RedpointSoundSubmix")
	}
	static class URedpointSoundSubmix* GetDefaultObj()
	{
		return GetDefaultObjImpl<URedpointSoundSubmix>();
	}
};
DUMPER7_ASSERTS_URedpointSoundSubmix;

// Class RedpointEOSVoiceChat.RedpointVoiceChatSoundWave
// 0x0060 (0x0460 - 0x0400)
class URedpointVoiceChatSoundWave final : public USoundWave
{
public:
	uint8                                         Pad_400[0x60];                                     // 0x0400(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RedpointVoiceChatSoundWave")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RedpointVoiceChatSoundWave")
	}
	static class URedpointVoiceChatSoundWave* GetDefaultObj()
	{
		return GetDefaultObjImpl<URedpointVoiceChatSoundWave>();
	}
};
DUMPER7_ASSERTS_URedpointVoiceChatSoundWave;

SDK_NAMESPACE_END
