#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RedpointEOSVoiceChat

#include "Basic.hpp"


SDK_NAMESPACE_START

// ScriptStruct RedpointEOSVoiceChat.RedpointOutputSoundEffectSubmixSettings
// 0x0070 (0x0070 - 0x0000)
struct alignas(0x08) FRedpointOutputSoundEffectSubmixSettings final
{
public:
	uint8                                         Pad_0[0x70];                                       // 0x0000(0x0070)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FRedpointOutputSoundEffectSubmixSettings;

SDK_NAMESPACE_END
