#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_SessionOptionString

#include "Basic.hpp"

#include "OnlineSubsystemBlueprints_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_SessionOptionString.ST_SessionOptionString
// 0x0020 (0x0020 - 0x0000)
struct FST_SessionOptionString final
{
public:
	class FName                                   Key_7_5B9C24EF437AEC24518707B1883AB99B;            // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Value_6_F14EEB8A4FBFC93B2DA1A787DAE283E6;          // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	EOnlineComparisonOp_                          SearchOption_9_08222B7A4D6B517EFDBE9CA94778CD18;   // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_SessionOptionString;

SDK_NAMESPACE_END
