#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Occlusion_Portal

#include "Basic.hpp"

#include "UDS_Occlusion_Portal_classes.hpp"


SDK_NAMESPACE_START

// Function UDS_Occlusion_Portal.UDS_Occlusion_Portal_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UUDS_Occlusion_Portal_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UDS_Occlusion_Portal_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
