#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CurrentWeight

#include "Basic.hpp"

#include "WBP_CurrentWeight_classes.hpp"
#include "WBP_CurrentWeight_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CurrentWeight.WBP_CurrentWeight_C.SetWeight
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CurrentWeight_C::SetWeight(double Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CurrentWeight_C", "SetWeight");

	Params::WBP_CurrentWeight_C_SetWeight Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CurrentWeight.WBP_CurrentWeight_C.SetValue
// (BlueprintCallable, BlueprintEvent)

void UWBP_CurrentWeight_C::SetValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CurrentWeight_C", "SetValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CurrentWeight.WBP_CurrentWeight_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CurrentWeight_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CurrentWeight_C", "PreConstruct");

	Params::WBP_CurrentWeight_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
