#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ShortageStamina

#include "Basic.hpp"

#include "WBP_ShortageStamina_classes.hpp"


SDK_NAMESPACE_START

// Function WBP_ShortageStamina.WBP_ShortageStamina_C.ShakePlay
// (BlueprintCallable, BlueprintEvent)

void UWBP_ShortageStamina_C::ShakePlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ShortageStamina_C", "ShakePlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
