#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ControllerGradientSlider

#include "Basic.hpp"

#include "WBP_ControllerGradientSlider_classes.hpp"
#include "WBP_ControllerGradientSlider_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.UpdateSliderBar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NormalizeValue                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ControllerGradientSlider_C::UpdateSliderBar(double NormalizeValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "UpdateSliderBar");

	Params::WBP_ControllerGradientSlider_C_UpdateSliderBar Parms{};

	Parms.NormalizeValue = NormalizeValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.SetSliderValue
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UpdateCall                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ControllerGradientSlider_C::SetSliderValue(double Value, bool UpdateCall)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "SetSliderValue");

	Params::WBP_ControllerGradientSlider_C_SetSliderValue Parms{};

	Parms.Value = Value;
	Parms.UpdateCall = UpdateCall;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.SetSelectState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelect                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ControllerGradientSlider_C::SetSelectState(bool IsSelect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "SetSelectState");

	Params::WBP_ControllerGradientSlider_C_SetSelectState Parms{};

	Parms.IsSelect = IsSelect;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.SetBarColor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ControllerGradientSlider_C::SetBarColor(const struct FLinearColor& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "SetBarColor");

	Params::WBP_ControllerGradientSlider_C_SetBarColor Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ControllerGradientSlider_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "PreConstruct");

	Params::WBP_ControllerGradientSlider_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ControllerGradientSlider_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.AddSliderValue
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ControllerGradientSlider_C::AddSliderValue(double Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ControllerGradientSlider_C", "AddSliderValue");

	Params::WBP_ControllerGradientSlider_C_AddSliderValue Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
