#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ImportMap

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ImportMap.WBP_ImportMap_C
// 0x0010 (0x0350 - 0x0340)
class UWBP_ImportMap_C final : public UUserWidget
{
public:
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UScrollBox*                             ScrollBox_72;                                      // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ImportMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ImportMap_C")
	}
	static class UWBP_ImportMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ImportMap_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ImportMap_C;

SDK_NAMESPACE_END
