#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LINK_StaminaBar

#include "Basic.hpp"

#include "WBP_LINK_StaminaBar_classes.hpp"
#include "WBP_LINK_StaminaBar_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_LINK_StaminaBar.WBP_LINK_StaminaBar_C.SetBarSize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_LINK_StaminaBar_C::SetBarSize(double NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_LINK_StaminaBar_C", "SetBarSize");

	Params::WBP_LINK_StaminaBar_C_SetBarSize Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_LINK_StaminaBar.WBP_LINK_StaminaBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_LINK_StaminaBar_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_LINK_StaminaBar_C", "PreConstruct");

	Params::WBP_LINK_StaminaBar_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
