#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CentorTextWinner

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_CentorTextWinner.WBP_CentorTextWinner_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_CentorTextWinner_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CentorTextWinner_C_PreConstruct;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
