#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoiceChatControlPanel

#include "Basic.hpp"

#include "WBP_VoiceChatControlPanel_classes.hpp"


SDK_NAMESPACE_START

// Function WBP_VoiceChatControlPanel.WBP_VoiceChatControlPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_VoiceChatControlPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatControlPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
