#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HealthAndStaminaBar

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_HealthAndStaminaBar.WBP_HealthAndStaminaBar_C
// 0x0028 (0x0368 - 0x0340)
class UWBP_HealthAndStaminaBar_C final : public UUserWidget
{
public:
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Bar_C*                             WBP_StaminaBar;                                    // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Bar_C*                             WBP_HealthBar;                                     // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             EnemyName;                                         // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       VisibleAnimation;                                  // 0x0360(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void VisibleState(bool State);
	void StaminaBarUpdateSub(double Value);
	void StaminaBarUpdate(double Value);
	void SetText(const class FText& Text, int32 Index_0);
	void SetColor(const struct FLinearColor& Color, int32 Index_0);
	void PlayAnimationMessage(bool IsForward, int32 Index_0);
	void HealthBarUpdateSub(double Value);
	void HealthBarUpdate(double Value);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_HealthAndStaminaBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_HealthAndStaminaBar_C")
	}
	static class UWBP_HealthAndStaminaBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HealthAndStaminaBar_C>();
	}
};
DUMPER7_ASSERTS_UWBP_HealthAndStaminaBar_C;

SDK_NAMESPACE_END
