#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GlueValueText

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GlueValueText.WBP_GlueValueText_C
// 0x0018 (0x0358 - 0x0340)
class UWBP_GlueValueText_C final : public UUserWidget
{
public:
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_UnderGuage_C*                      WBP_UnderGuage;                                    // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             MainTextBlock;                                     // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateBarWidth();
	void SetText(const class FText& InText);
	void SetBarWidth(double Desired_Size_X);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GlueValueText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GlueValueText_C")
	}
	static class UWBP_GlueValueText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GlueValueText_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GlueValueText_C;

SDK_NAMESPACE_END
