#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ConfigSound

#include "Basic.hpp"

#include "WBP_ConfigSound_classes.hpp"
#include "WBP_ConfigSound_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ConfigSound.WBP_ConfigSound_C.ScreenTypeSettingsUpdate
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ConfigSound_C::ScreenTypeSettingsUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "ScreenTypeSettingsUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ConfigSound_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "PreConstruct");

	Params::WBP_ConfigSound_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.DeleteConfigWidget
// (BlueprintCallable, BlueprintEvent)

void UWBP_ConfigSound_C::DeleteConfigWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "DeleteConfigWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ConfigSound_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.BndEvt__WBP_ConfigSound_WBP_TextSE_K2Node_ComponentBoundEvent_1_UpdateSettingValue__DelegateSignature
// (BlueprintEvent)

void UWBP_ConfigSound_C::BndEvt__WBP_ConfigSound_WBP_TextSE_K2Node_ComponentBoundEvent_1_UpdateSettingValue__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "BndEvt__WBP_ConfigSound_WBP_TextSE_K2Node_ComponentBoundEvent_1_UpdateSettingValue__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.BndEvt__WBP_ConfigSound_WBP_SE_K2Node_ComponentBoundEvent_0_UpdateSettingValue__DelegateSignature
// (BlueprintEvent)

void UWBP_ConfigSound_C::BndEvt__WBP_ConfigSound_WBP_SE_K2Node_ComponentBoundEvent_0_UpdateSettingValue__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "BndEvt__WBP_ConfigSound_WBP_SE_K2Node_ComponentBoundEvent_0_UpdateSettingValue__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.BndEvt__WBP_ConfigSound_WBP_BGM_K2Node_ComponentBoundEvent_2_UpdateSettingValue__DelegateSignature
// (BlueprintEvent)

void UWBP_ConfigSound_C::BndEvt__WBP_ConfigSound_WBP_BGM_K2Node_ComponentBoundEvent_2_UpdateSettingValue__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "BndEvt__WBP_ConfigSound_WBP_BGM_K2Node_ComponentBoundEvent_2_UpdateSettingValue__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConfigSound.WBP_ConfigSound_C.ApplySettings
// (BlueprintCallable, BlueprintEvent)

void UWBP_ConfigSound_C::ApplySettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConfigSound_C", "ApplySettings");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
