#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChooseBody

#include "Basic.hpp"

#include "WBP_ChooseBody_classes.hpp"
#include "WBP_ChooseBody_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ChooseBody.WBP_ChooseBody_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChooseBody_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChooseBody_C", "PreConstruct");

	Params::WBP_ChooseBody_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChooseBody.WBP_ChooseBody_C.OnClickWithClass
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_BodySelect_C*                SelfObject                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UClass*                           BodyClass                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ChooseBody_C::OnClickWithClass(class UWBP_BodySelect_C* SelfObject, class UClass* BodyClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChooseBody_C", "OnClickWithClass");

	Params::WBP_ChooseBody_C_OnClickWithClass Parms{};

	Parms.SelfObject = SelfObject;
	Parms.BodyClass = BodyClass;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
