#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Pause

#include "Basic.hpp"

#include "WBP_Pause_classes.hpp"
#include "WBP_Pause_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Pause.WBP_Pause_C.OnReturn
// (Event, Public, BlueprintEvent)

void UWBP_Pause_C::OnReturn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "OnReturn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Pause.WBP_Pause_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Pause_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Pause.WBP_Pause_C.OnDestroySessionComplete_E73CF3A14099BA1780F00197E2D8169E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Pause_C::OnDestroySessionComplete_E73CF3A14099BA1780F00197E2D8169E(class FName SessionName, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "OnDestroySessionComplete_E73CF3A14099BA1780F00197E2D8169E");

	Params::WBP_Pause_C_OnDestroySessionComplete_E73CF3A14099BA1780F00197E2D8169E Parms{};

	Parms.SessionName = SessionName;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Pause.WBP_Pause_C.OnCallFailed_E73CF3A14099BA1780F00197E2D8169E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Pause_C::OnCallFailed_E73CF3A14099BA1780F00197E2D8169E(class FName SessionName, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "OnCallFailed_E73CF3A14099BA1780F00197E2D8169E");

	Params::WBP_Pause_C_OnCallFailed_E73CF3A14099BA1780F00197E2D8169E Parms{};

	Parms.SessionName = SessionName;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Pause.WBP_Pause_C.GetInitialFocusComponent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUINavComponent*                  ReturnValue_GetInitialFocusComponent                   (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UUINavComponent* UWBP_Pause_C::GetInitialFocusComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "GetInitialFocusComponent");

	Params::WBP_Pause_C_GetInitialFocusComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Pause.WBP_Pause_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Pause_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Pause.WBP_Pause_C.BndEvt__WBP_Pause_LongTapButton_VoiceChat_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Pause_C::BndEvt__WBP_Pause_LongTapButton_VoiceChat_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "BndEvt__WBP_Pause_LongTapButton_VoiceChat_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Pause.WBP_Pause_C.BndEvt__WBP_Pause_LongTapButton_Settings_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Pause_C::BndEvt__WBP_Pause_LongTapButton_Settings_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "BndEvt__WBP_Pause_LongTapButton_Settings_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Pause.WBP_Pause_C.BndEvt__WBP_Pause_LongTapButton_BackToHome_K2Node_ComponentBoundEvent_4_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Pause_C::BndEvt__WBP_Pause_LongTapButton_BackToHome_K2Node_ComponentBoundEvent_4_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "BndEvt__WBP_Pause_LongTapButton_BackToHome_K2Node_ComponentBoundEvent_4_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Pause.WBP_Pause_C.BndEvt__WBP_Pause_LongTapButton_BackGame_K2Node_ComponentBoundEvent_3_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Pause_C::BndEvt__WBP_Pause_LongTapButton_BackGame_K2Node_ComponentBoundEvent_3_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Pause_C", "BndEvt__WBP_Pause_LongTapButton_BackGame_K2Node_ComponentBoundEvent_3_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
